### ISSUE TITLE
ConductorMVP + RxJava?

### ISSUE THREAD

**Issue by PedroAlvarado** [jshvarts/ConductorMVP#3]
This boilerplate/demo project with Conductor over MVP is perhaps one of the best out there. It'd be great to see your take on RxJava on top of this work. It would make another great medium post. 

Again, great work!

**Comment by estelle-peterson** [comment]
+1

**Comment by jshvarts** [comment]
Thanks! Can you clarify what kind of Conductor MVP + RxJava work you are talking about? The data layer of this app is already RxJava and you can see it in the Presenter, Domain and Data layer code.

**Comment by PedroAlvarado** [comment]
Allow me to close this issue. What was going through my mind is the usage of RxBinding + Conductor + Uni-directional data flow. I see you have another great example in the MosbyMvi repo which covers a lot of what was I thinking. Maybe, a non-mosby-based MVI implementation could be interesting to see but that is something else. Again, awesome demos!
