### ISSUE TITLE
Why is data layer defined as "android library" plugin?

### ISSUE THREAD

**Issue by urosjarc** [jshvarts/ConductorMVP#6]
I'm confused with the fact that you are using ["android library" in data layer](https://github.com/jshvarts/ConductorMVP/blob/master/data/build.gradle#L1) because the data layer should not know what is happening on the presentation layer...

Why is it so? Did I miss something?

**Comment by jshvarts** [comment]
The data layer currently uses Room which is Android arch component so it needs to be an Android library.
